Manipulating time derivative forms
firedrakeproject/Irksome pull request #37
Opened 2022-04-07 17:19 UTC by rckirby

Previously, the facility to split terms with time derivatives from the rest of a form was broken in the case of taking `Dt` of a piece of a mixed function space.  This fixes that and adds a test to check.

2022-04-07 18:28 UTC, wence- commented on irksome/manipulation.py
> +                         f"coeffficients, not {len(time_derivatives - {()})}")
This is a regression from main which you should drop.

2022-04-07 18:28 UTC, wence- commented on irksome/manipulation.py
> +    check_integrals(rest_terms, expect_time_derivative=False)
This is regression from main which you should drop.

2022-04-07 18:28 UTC, wence- commented on irksome/manipulation.py
> +    raise AssertionError
This is a regression from main which you should drop.

2022-04-07 18:28 UTC, wence- commented on irksome/manipulation.py
> +    terminals = tuple(set([x for x in traverse_unique_terminals(op) if not isinstance(x, MultiIndex)]))
I think this looks right.

2022-04-07 18:29 UTC, wence- requested changes
Somehow this removes a bunch of return values and informational stuff.

2022-04-07 22:38 UTC, ScottMacLachlan reviewed
I have nothing to add to this discussion

2022-04-08 11:49 UTC, wence- approved these changes

2022-04-08 11:50 UTC, merged